- assets/samplesheet.csv
- assets/schema_input.json
- conf/test.config
- subworkflows/local/utils_nfcore_lr_somatic_pipeline/main.nf
Including link to test samplesheet
> Adding samplesheet

- modules.json
adding the forgotten changes is modules.json file
> add modules.json with samtools stats flagstat and idxstats

- CHANGELOG.md
- conf/modules.config
- modules.json
- subworkflows/local/run_minimap2_align.nf
- subworkflows/nf-core/bam_stats_samtools/main.nf
- subworkflows/nf-core/bam_stats_samtools/meta.yml
- subworkflows/nf-core/bam_stats_samtools/tests/main.nf.test
- subworkflows/nf-core/bam_stats_samtools/tests/main.nf.test.snap
- subworkflows/nf-core/bam_stats_samtools/tests/tags.yml
- workflows/lr_somatic.nf
> Samtools stats

- modules/local/cramino/main.nf
- workflows/lr_somatic.nf
adding cramino pre and post alignment to the workflow
> add cramino to the main lr_somatic.nf workflow

- CHANGELOG.md
- conf/modules.config
- workflows/lr_somatic.nf
add mosdepth to the main workflow
> add mosdepth to workflow

- CHANGELOG.md
- docs/output.md
- modules.json
- modules/nf-core/longphase/haplotag/environment.yml
- modules/nf-core/longphase/haplotag/main.nf
- modules/nf-core/longphase/haplotag/meta.yml
- modules/nf-core/longphase/haplotag/tests/main.nf.test
- modules/nf-core/longphase/haplotag/tests/main.nf.test.snap
- modules/nf-core/longphase/haplotag/tests/nextflow.config
- modules/nf-core/longphase/haplotag/tests/tags.yml
- modules/nf-core/longphase/phase/environment.yml
- modules/nf-core/longphase/phase/main.nf
- modules/nf-core/longphase/phase/meta.yml
- modules/nf-core/longphase/phase/tests/main.nf.test
- modules/nf-core/longphase/phase/tests/main.nf.test.snap
- modules/nf-core/longphase/phase/tests/nextflow.config
- modules/nf-core/longphase/phase/tests/tags.yml
> add longphase modules

- assets/samplesheet.csv
- assets/schema_input.json
- conf/modules.config
- conf/test.config
- modules.json
- modules/local/clair3/environment.yml
- modules/local/clair3/main.nf
- modules/local/clair3/meta.yml
- modules/local/clair3/tests/main.nf.test
- modules/local/metaextract/environment.yml
- modules/local/metaextract/main.nf
- modules/local/metaextract/meta.yml
- modules/local/metaextract/tests/main.nf.test
- modules/nf-core/samtools/index/environment.yml
- modules/nf-core/samtools/index/main.nf
- modules/nf-core/samtools/index/meta.yml
- modules/nf-core/samtools/index/tests/csi.nextflow.config
- modules/nf-core/samtools/index/tests/main.nf.test
- modules/nf-core/samtools/index/tests/main.nf.test.snap
- modules/nf-core/samtools/index/tests/tags.yml
- modules/nf-core/severus/main.nf
- nextflow.config
- subworkflows/local/run_clair.nf
- subworkflows/local/utils_nfcore_lr_somatic_pipeline/main.nf
- workflows/lr_somatic.nf
Adds pipeline from clair3 to severus
> Clair split

- assets/samplesheet.csv
- conf/modules.config
- conf/test.config
- modules.json
- modules/local/clair3/main.nf
- modules/local/metaextract/main.nf
- modules/local/wakhan/environment.yml
- modules/local/wakhan/main.nf
- modules/local/wakhan/meta.yml
- modules/local/wakhan/tests/main.nf.test
- modules/nf-core/ascat/ascat.diff
- modules/nf-core/ascat/environment.yml
- modules/nf-core/ascat/main.nf
- modules/nf-core/ascat/meta.yml
- modules/nf-core/longphase/haplotag/main.nf
- modules/nf-core/longphase/phase/main.nf
- modules/nf-core/unzip/environment.yml
- modules/nf-core/unzip/main.nf
- modules/nf-core/unzip/meta.yml
- modules/nf-core/unzip/tests/main.nf.test
- modules/nf-core/unzip/tests/main.nf.test.snap
- modules/nf-core/unzip/tests/tags.yml
- nextflow.config
- subworkflows/local/prepare_reference_files.nf
- workflows/lr_somatic.nf
> Cna callers

- modules/local/wakhan/main.nf
- subworkflows/local/prepare_reference_files.nf
- subworkflows/local/tumor_normal_happhase.nf
- workflows/lr_somatic.nf
> Adding wakhan, some versioning, and code formatting 

- conf/modules.config
- conf/test.config
> Added online testdata

- modules/local/clair3/main.nf
- modules/local/clair3/meta.yml
- modules/local/clair3/tests/main.nf.test
- modules/local/clair3/tests/main.nf.test.snap
- modules/local/clairs/environment.yml
- modules/local/clairs/main.nf
- modules/local/clairs/meta.yml
- modules/local/clairs/tests/main.nf.test
- modules/local/clairs/tests/main.nf.test.snap
- modules/local/clairsto/environment.yml
- modules/local/clairsto/main.nf
- modules/local/clairsto/meta.yml
- modules/local/clairsto/tests/main.nf.test
- modules/local/clairsto/tests/main.nf.test.snap
- subworkflows/local/tumor_normal_happhase.nf
- subworkflows/local/tumor_only_happhase.nf
- subworkflows/local/utils_nfcore_lr_somatic_pipeline/main.nf
- workflows/lr_somatic.nf
> Nfcore standardizing

- README.md
> Introduction for README

- README.md
> output docs

- README.md
> Pipeline summary  for README

- conf/modules.config
- modules/local/clair3/main.nf
- modules/local/clairs/main.nf
- workflows/lr_somatic.nf
> Quick fixes

- assets/samplesheet.csv
- conf/modules.config
- conf/test.config
- modules/nf-core/ascat/ascat.diff
- modules/nf-core/ascat/main.nf
- workflows/lr_somatic.nf
> fixed ascat and some minor samplesheet stuff

- conf/modules.config
> fixed samtools output

- README.md
- conf/igenomes.config
- conf/modules.config
- nextflow_schema.json
- workflows/lr_somatic.nf
> Small_fixes

- conf/igenomes.config
- conf/modules.config
> changed ascat to own github

- conf/modules.config
- nextflow.config
> keeps pacbio kinetics info

- conf/modules.config
- modules/nf-core/ascat/ascat.diff
- modules/nf-core/ascat/main.nf
- nextflow.config
> added ascat penalty parameter and removed longphase germline.vcf.gz from final output

- workflows/lr_somatic.nf
> skip fixes

- conf/modules.config
> Indel phasing to longphase

- conf/modules.config
- modules/local/clairsto/main.nf
- workflows/lr_somatic.nf
> output structure changes

- modules/nf-core/ascat/ascat.diff
- modules/nf-core/ascat/main.nf
> ascat output fixes

- modules/nf-core/severus/main.nf
> update severus to 1.6

- modules/nf-core/ascat/main.nf
- workflows/lr_somatic.nf
#63 just for easy usage for the latest model support
> Add support to new dorado models

- modules/local/vcfsplit/main.nf
- subworkflows/local/tumor_only_happhase.nf
- workflows/lr_somatic.nf
> fix vcf split modules

- workflows/lr_somatic.nf
Removed ANNOTSV_ANNOTSV import from lr_somatic.nf
> Remove ANNOTSV_ANNOTSV import
